# Generated by Django 3.2.8 on 2021-11-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccin', '0002_vaccin_prix'),
        ('centre', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='centre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.centre', verbose_name='Centre'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='vaccin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccin.vaccin', verbose_name='Vaccin'),
        ),
    ]
