# Generated by Django 3.2.8 on 2021-11-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccin',
            name='prix',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
    ]
