# Generated by Django 3.2.8 on 2021-11-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccin', '0002_vaccin_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccin',
            name='prix',
        ),
    ]
